"use client";

import { useApi } from "@/hooks/use-api";
import { Card } from "@/components/card";
import { AppShell } from "@/components/app-shell";

interface ArbTenor {
  tenor: number;
  contractMonth: string;
  forwardPrice: number;
  spotPrice: number;
  contangoPerBbl: number;
  freightPerBbl: number;
  financingPerBbl: number;
  insurancePerBbl: number;
  profitPerBbl: number;
  profitable: boolean;
}

interface ArbReport {
  generatedAt: string;
  instrument: string;
  spotPrice: number | null;
  vlccTCEPerDay: number | null;
  bdti: number | null;
  tenors: ArbTenor[];
  best: ArbTenor | null;
  recommendation: string;
  sentiment: "bullish_storage" | "neutral" | "no_arb";
}

interface StorageCandidate {
  mmsi: number;
  name: string | null;
  isVLCC: boolean;
  idleDays: number;
  avgSpeed: number;
  draught: number | null;
  lat: number;
  lng: number;
}

interface StorageReport {
  totals: { candidatesAll: number; vlcc: number; suezmaxOrSmaller: number };
  estimatedBarrels: number;
  candidates: StorageCandidate[];
}

interface OpecCountry {
  country: string;
  quotaKbd: number;
  estimatedKbd: number;
  compliancePct: number;
  delta: number;
  over: boolean;
  loadings: number;
}

interface OpecReport {
  generatedAt: string;
  countries: OpecCountry[];
  totalQuotaKbd: number;
  totalEstimatedKbd: number;
  groupCompliancePct: number;
  alerts: string[];
}

interface CurveStructure {
  shape: "contango" | "backwardation" | "flat";
  m1: number;
  m6: number;
  m12: number | null;
  spread6m: number;
  spread12m: number | null;
}

interface ChokepointReport {
  id: string;
  name: string;
  share: string;
  strategic: string;
  current: { tankers: number; cargo: number; total: number; avgSpeed: number };
  transit24h: number;
  avg7d: number;
  changePct: number;
  status: "normal" | "elevated" | "depressed" | "no-data";
  alert: string | null;
}

interface ChokepointFlow {
  generatedAt: string;
  globalAlerts: string[];
  chokepoints: ChokepointReport[];
}

interface SignalsPayload {
  generatedAt: string;
  storage: StorageReport | { error: string };
  arbitrage: { brent: ArbReport; wti: ArbReport };
  opec: OpecReport | { error: string };
  structure: { brent: CurveStructure | null; wti: CurveStructure | null };
  bdti: { value: number; source: string; fetchedAt: string } | null;
  chokepoints: ChokepointFlow | { error: string };
}

const usd = (n: number) => `$${n.toLocaleString("en-US", { maximumFractionDigits: 2 })}`;

function sentimentColor(s: string) {
  if (s === "bullish_storage") return "bg-emerald-100 text-emerald-900";
  if (s === "neutral") return "bg-amber-100 text-amber-900";
  return "bg-zinc-100 text-zinc-700";
}

export default function SignalsPage() {
  const { data, loading, error } = useApi<SignalsPayload>("/api/signals", 120_000);

  return (
    <AppShell>
      <div className="px-4 sm:px-6 md:px-8 pt-8 pb-16 max-w-[1400px] mx-auto">
        <div className="mb-6">
          <h1 className="text-[28px] font-semibold tracking-tight text-text">
            Institutional Signals
          </h1>
          <p className="text-[13px] text-text2 mt-1">
            Floating storage detection · Contango arbitrage · OPEC+ compliance · Crack spread
            <span className="block mt-1 text-[11px]">
              Generated by combining live AISStream, BDTI, and forward-curve data.
              These signals do not exist in any retail terminal.
            </span>
          </p>
        </div>

        {loading && <div className="text-text2">Computing signals…</div>}
        {error && (
          <div className="bg-amber-50 border border-amber-200 text-amber-900 p-4 rounded mb-6 text-sm">
            {error} — Did you start the AIS worker (<code>npm run worker:ais</code>) and run the price cron?
          </div>
        )}

        {data && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
            {/* ─── Contango arbitrage ─────────────────────── */}
            <Card title="Contango Arbitrage — Brent" badge={{ text: data.arbitrage.brent.sentiment.replace("_", " "), variant: "accent" }}>
              <ArbBlock report={data.arbitrage.brent} />
            </Card>

            <Card title="Contango Arbitrage — WTI">
              <ArbBlock report={data.arbitrage.wti} />
            </Card>

            {/* ─── Floating storage ─────────────────────── */}
            <Card
              title="Floating Storage Detector"
              badge={
                "totals" in data.storage
                  ? { text: `${data.storage.totals.candidatesAll} ships`, variant: "dark" }
                  : undefined
              }
              className="lg:col-span-2"
            >
              {"error" in data.storage ? (
                <div className="text-text2 text-sm">{data.storage.error}</div>
              ) : (
                <FloatingStorageBlock storage={data.storage} />
              )}
            </Card>

            {/* ─── Chokepoints ─────────────────────── */}
            <Card
              title="Oil Chokepoint Flow"
              badge={
                "globalAlerts" in data.chokepoints && data.chokepoints.globalAlerts.length > 0
                  ? { text: `${data.chokepoints.globalAlerts.length} alerts`, variant: "accent" }
                  : { text: "live", variant: "dark" }
              }
              className="lg:col-span-2"
            >
              {"error" in data.chokepoints ? (
                <div className="text-text2 text-sm">{data.chokepoints.error}</div>
              ) : (
                <ChokepointsBlock cp={data.chokepoints} />
              )}
            </Card>

            {/* ─── OPEC+ compliance ─────────────────────── */}
            <Card
              title="OPEC+ Compliance Scoring"
              badge={
                "groupCompliancePct" in data.opec
                  ? { text: `${data.opec.groupCompliancePct}% of quota`, variant: data.opec.groupCompliancePct > 105 ? "accent" : "dark" }
                  : undefined
              }
              className="lg:col-span-2"
            >
              {"error" in data.opec ? (
                <div className="text-text2 text-sm">{data.opec.error}</div>
              ) : (
                <OpecBlock opec={data.opec} />
              )}
            </Card>

            {/* ─── Curve structure ─────────────────────── */}
            <Card title="Forward Curve Structure">
              <StructureBlock label="Brent" s={data.structure.brent} />
              <div className="h-3" />
              <StructureBlock label="WTI" s={data.structure.wti} />
            </Card>

            <Card title="BDTI — Tanker Freight Index">
              {data.bdti ? (
                <>
                  <div className="text-[32px] font-semibold text-text leading-none">
                    {data.bdti.value.toLocaleString()}
                  </div>
                  <div className="text-[11px] text-text2 mt-1">
                    Source: {data.bdti.source} · {new Date(data.bdti.fetchedAt).toLocaleString()}
                  </div>
                  <div className="text-[12px] text-text2 mt-3">
                    Implied VLCC TCE ≈ {usd(Math.round(data.bdti.value * 18 - 8000))}/day (heuristic)
                  </div>
                </>
              ) : (
                <div className="text-text2 text-sm">No BDTI yet. Run /api/cron/bdti.</div>
              )}
            </Card>
          </div>
        )}

        {data && (
          <div className="mt-6 text-[11px] text-text2">
            Last computed: {new Date(data.generatedAt).toLocaleString()}
          </div>
        )}
      </div>
    </AppShell>
  );
}

function ArbBlock({ report }: { report: ArbReport }) {
  if (report.spotPrice == null) {
    return <div className="text-text2 text-sm">{report.recommendation}</div>;
  }
  return (
    <div>
      <div className="flex items-center gap-3 mb-3">
        <div className={`text-[10px] px-2 py-[3px] rounded-full font-semibold ${sentimentColor(report.sentiment)}`}>
          {report.sentiment.replace("_", " ").toUpperCase()}
        </div>
        <div className="text-[12px] text-text2">
          Spot {usd(report.spotPrice)} · BDTI {report.bdti ?? "—"} · TCE {report.vlccTCEPerDay ? usd(report.vlccTCEPerDay) + "/d" : "—"}
        </div>
      </div>
      <div className="text-[13px] text-text mb-3">{report.recommendation}</div>
      {report.tenors.length > 0 && (
        <div className="overflow-x-auto -mx-6 px-6">
          <table className="w-full text-[12px]">
            <thead className="text-text2 text-left">
              <tr>
                <th className="py-1 pr-3">Tenor</th>
                <th className="py-1 pr-3">Fwd</th>
                <th className="py-1 pr-3">Contango</th>
                <th className="py-1 pr-3">Freight</th>
                <th className="py-1 pr-3">Fin+Ins</th>
                <th className="py-1 pr-3">P/L $/bbl</th>
              </tr>
            </thead>
            <tbody>
              {report.tenors.map((t) => (
                <tr key={t.tenor} className={t.profitable ? "bg-emerald-50" : ""}>
                  <td className="py-1 pr-3 font-mono">{t.tenor}M</td>
                  <td className="py-1 pr-3">{usd(t.forwardPrice)}</td>
                  <td className="py-1 pr-3">{usd(t.contangoPerBbl)}</td>
                  <td className="py-1 pr-3">{usd(t.freightPerBbl)}</td>
                  <td className="py-1 pr-3">{usd(t.financingPerBbl + t.insurancePerBbl)}</td>
                  <td className={`py-1 pr-3 font-semibold ${t.profitPerBbl > 0 ? "text-emerald-700" : "text-zinc-500"}`}>
                    {usd(t.profitPerBbl)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

function FloatingStorageBlock({ storage }: { storage: StorageReport }) {
  return (
    <div>
      <div className="grid grid-cols-3 gap-3 mb-4">
        <Stat label="Candidates" value={storage.totals.candidatesAll.toString()} />
        <Stat label="VLCC class" value={storage.totals.vlcc.toString()} />
        <Stat
          label="Estimated barrels"
          value={`${(storage.estimatedBarrels / 1_000_000).toFixed(1)}M`}
        />
      </div>
      {storage.candidates.length === 0 ? (
        <div className="text-text2 text-sm">
          No tanker matches the floating-storage signature in the last 7 days.
        </div>
      ) : (
        <div className="overflow-x-auto -mx-6 px-6 max-h-[360px] overflow-y-auto">
          <table className="w-full text-[12px]">
            <thead className="text-text2 text-left sticky top-0 bg-bg3">
              <tr>
                <th className="py-1 pr-3">Vessel</th>
                <th className="py-1 pr-3">Class</th>
                <th className="py-1 pr-3">Idle days</th>
                <th className="py-1 pr-3">Avg speed</th>
                <th className="py-1 pr-3">Position</th>
              </tr>
            </thead>
            <tbody>
              {storage.candidates.slice(0, 50).map((c) => (
                <tr key={c.mmsi}>
                  <td className="py-1 pr-3 font-medium">{c.name ?? `MMSI ${c.mmsi}`}</td>
                  <td className="py-1 pr-3">{c.isVLCC ? "VLCC" : "Other"}</td>
                  <td className="py-1 pr-3">{c.idleDays}</td>
                  <td className="py-1 pr-3">{c.avgSpeed} kn</td>
                  <td className="py-1 pr-3 font-mono text-[11px]">
                    {c.lat.toFixed(2)}, {c.lng.toFixed(2)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

function OpecBlock({ opec }: { opec: OpecReport }) {
  return (
    <div>
      <div className="grid grid-cols-3 gap-3 mb-4">
        <Stat label="Total quota" value={`${(opec.totalQuotaKbd / 1000).toFixed(1)} mb/d`} />
        <Stat label="Estimated loadings" value={`${(opec.totalEstimatedKbd / 1000).toFixed(1)} mb/d`} />
        <Stat label="Group compliance" value={`${opec.groupCompliancePct}%`} />
      </div>
      {opec.alerts.length > 0 && (
        <div className="bg-amber-50 border border-amber-200 text-amber-900 p-3 rounded mb-3 text-[12px]">
          {opec.alerts.map((a, i) => (
            <div key={i}>• {a}</div>
          ))}
        </div>
      )}
      <div className="overflow-x-auto -mx-6 px-6">
        <table className="w-full text-[12px]">
          <thead className="text-text2 text-left">
            <tr>
              <th className="py-1 pr-3">Country</th>
              <th className="py-1 pr-3">Quota kb/d</th>
              <th className="py-1 pr-3">Estimated</th>
              <th className="py-1 pr-3">Δ</th>
              <th className="py-1 pr-3">% quota</th>
              <th className="py-1 pr-3">Loadings (30d)</th>
            </tr>
          </thead>
          <tbody>
            {opec.countries.map((c) => (
              <tr key={c.country} className={c.over ? "bg-rose-50" : ""}>
                <td className="py-1 pr-3 font-medium">{c.country}</td>
                <td className="py-1 pr-3">{c.quotaKbd.toLocaleString()}</td>
                <td className="py-1 pr-3">{c.estimatedKbd.toLocaleString()}</td>
                <td className={`py-1 pr-3 font-semibold ${c.delta > 0 ? "text-rose-700" : "text-emerald-700"}`}>
                  {c.delta > 0 ? "+" : ""}{c.delta}
                </td>
                <td className="py-1 pr-3">{c.compliancePct}%</td>
                <td className="py-1 pr-3">{c.loadings}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function ChokepointsBlock({ cp }: { cp: ChokepointFlow }) {
  return (
    <div>
      {cp.globalAlerts.length > 0 && (
        <div className="bg-rose-50 border border-rose-200 text-rose-900 p-3 rounded mb-3 text-[12px]">
          {cp.globalAlerts.map((a, i) => (
            <div key={i}>⚠ {a}</div>
          ))}
        </div>
      )}
      <div className="overflow-x-auto -mx-6 px-6">
        <table className="w-full text-[12px]">
          <thead className="text-text2 text-left">
            <tr>
              <th className="py-1 pr-3">Chokepoint</th>
              <th className="py-1 pr-3">% global oil</th>
              <th className="py-1 pr-3">Now (tankers)</th>
              <th className="py-1 pr-3">24h transits</th>
              <th className="py-1 pr-3">7d avg</th>
              <th className="py-1 pr-3">Δ %</th>
              <th className="py-1 pr-3">Status</th>
            </tr>
          </thead>
          <tbody>
            {cp.chokepoints.map((c) => {
              const color =
                c.status === "depressed" ? "bg-rose-50" :
                c.status === "elevated" ? "bg-amber-50" : "";
              const deltaColor =
                c.changePct <= -20 ? "text-rose-700 font-semibold" :
                c.changePct >= 20 ? "text-amber-700 font-semibold" :
                "text-text2";
              return (
                <tr key={c.id} className={color}>
                  <td className="py-1 pr-3 font-medium">{c.name}</td>
                  <td className="py-1 pr-3 text-text2">{c.share}</td>
                  <td className="py-1 pr-3">{c.current.tankers}</td>
                  <td className="py-1 pr-3">{c.transit24h}</td>
                  <td className="py-1 pr-3">{c.avg7d || "—"}</td>
                  <td className={`py-1 pr-3 ${deltaColor}`}>
                    {c.avg7d > 0 ? `${c.changePct > 0 ? "+" : ""}${c.changePct}%` : "—"}
                  </td>
                  <td className="py-1 pr-3 uppercase text-[10px]">{c.status}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      <div className="mt-3 text-[11px] text-text2">
        Tip: a sustained −20% in Hormuz/Bab-el-Mandeb usually leads crude prices by 24–72h.
      </div>
    </div>
  );
}

function StructureBlock({ label, s }: { label: string; s: CurveStructure | null }) {
  if (!s) return <div className="text-text2 text-sm">{label}: no curve data</div>;
  const color =
    s.shape === "contango" ? "text-emerald-700" :
    s.shape === "backwardation" ? "text-rose-700" : "text-text2";
  return (
    <div className="flex items-baseline justify-between">
      <span className="text-[13px] text-text">{label}</span>
      <span className={`text-[12px] font-semibold ${color}`}>
        {s.shape.toUpperCase()} · M1 {usd(s.m1)} · 6M Δ {usd(s.spread6m)}
      </span>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-bg2 border border-border rounded-md p-3">
      <div className="text-[10px] uppercase tracking-wide text-text2">{label}</div>
      <div className="text-[20px] font-semibold text-text mt-1">{value}</div>
    </div>
  );
}
